Openai_API_Key: 
PDF_Name: The Power of Assertions in SystemVerilog
PDF_Txt: AllTextbooks.txt
JasperGold_VERIFY: 1
Model_Name: codellama:13b-instruct
Excute_Folder: ALL_DESIGNS
Excute_Folders_nl2spec: [eth_rxstatem, Gray_To_Binary, delay, arb2, Edge_Detector, VGA, simple_router, a25_wishbone, second_largest, reversing_bits, or1200_ctrl]
Excute_Folders_RAG: [a25_wishbone, second_largest, reversing_bits, or1200_ctrl]
Excute_Folders_Dynamic_RAG: [ff, BusArbiter, eth_rxstatem, Gray_To_Binary, delay, arb2, Edge_Detector, VGA, simple_router, a25_wishbone, second_largest, reversing_bits, or1200_ctrl]